# **Numpy**
<img src="https://numpy.org/images/logo.svg" alt="NumPy Logo" width="100" height="100"> 


**NumPy is a powerful open-source Python library primarily used for numerical and scientific computing. It provides support for creating and manipulating large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.**
### Key Points:

- **Core Data Structure** : The central feature of NumPy is the ndarray (N-dimensional array), which is a grid of values, all of the same type, indexed by a tuple of non-negative integers.

- **Mathematical Operations** : NumPy supports a wide range of mathematical operations, such as:
    Element-wise operations (addition, subtraction, etc.)
    Matrix operations (dot product, transpose)
    Statistical functions (mean, median, standard deviation)
    Trigonometric, exponential, and logarithmic functions

- **Broadcasting** : This feature allows operations on arrays of different shapes, making array calculations more intuitive and concise.

- **Efficiency** : NumPy is much faster than traditional Python lists for numerical tasks due to its implementation in C, enabling efficient memory management and computation.

- **Integration** : NumPy is foundational for many other Python libraries, including Pandas for data manipulation, SciPy for scientific computations, and Matplotlib for data visualization.

In [1]:
import numpy as np
print(np.__version__)

1.26.4


# Compare Numpy array vs python list in terms of **Time** & **Speed**
 - Numpy is almost 50 times faster than python list
 - Numpy use ctype array. Its a static array, not a referecial array

## Python list vs Numpy array Time compare

In [6]:
import time

# python lists
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]
c = []
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print("Operation time for python List :",time.time() - start)

Operation time for python List : 1.2276215553283691


In [7]:
import time
import numpy as np
# Numpy arrays
start = time.time()
import numpy as np
start = time.time()
a = np.arange(10000000)
b = np.arange(10000000, 20000000)
c = a + b 
print("Operation time for Numpy array :",time.time() - start)

Operation time for Numpy array : 0.29837918281555176


## Compare Numpy array vs python list in terms of memory

In [10]:
import sys
x = [i for i in range(10000000)] 
print("python list memory consume :",sys.getsizeof(x))

y = np.arange(10000000)
print("Numpy array memory consume :",sys.getsizeof(y))

z = np.arange(10000000, dtype='int8')
print("Numpy array memory consume :",sys.getsizeof(y))

# for store in small memory size
# b = np.arange(10000000, dtype = np.int32) , int8, 

python list memory consume : 89095160
Numpy array memory consume : 40000112
Numpy array memory consume : 40000112


# Broadcasting
- The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations
- The smaller array is "broadcast" across the larger array so that they have compatible shapes

In [13]:
import numpy as np
x = np.arange(6).reshape(2, 3)
print(x)

[[0 1 2]
 [3 4 5]]


In [14]:
y = np.arange(6, 12).reshape(2, 3)
print(y)

[[ 6  7  8]
 [ 9 10 11]]


In [15]:
# apply summetion on 2d numpy arrays
print(x+y)

[[ 6  8 10]
 [12 14 16]]


In [16]:
z = np.arange(3).reshape(1, 3)
print(z)

[[0 1 2]]


In [23]:
# print(x+z)
print(x+z)
# How it possible !? 
# Ans: Because its broadcasting. The smaller array is "broadcast" across the larger array so that they have compatible shape

[[0 2 4]
 [3 5 7]]


## Broadcasting rule

In [24]:
### Boradcasting rule
# 1. Make the two arrays have same number of dimentions
#    if the numbers of dimentions of the two arrays are different,add new dimensions with size 1 to the head of the array with the smaller dimensions like
# [3 2] , [3  ] 
# [3 2] , [1 3]

# [3 3 3] [3]
# [3 3 3] [1 1 3]

# 2. Make each dimentions of two arrays the same size .
#    if the sizes of each dimension of the two arrays do not match, dimentions with size 1 are stretched to the size of the other array

# [3 3]   [3]
#         [1 3]
# [3 3]   [3 3]


# [4 3]   [3]
#         [1 3]
# [4 3]   [4 3]

#    if threre is a dimesion whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised

# [3 4]  [3]
# [3 4]  [1 3]
# [3 4]  [4 3] 
# both dimentions are not matching so it wil rasie error

In [27]:
# example 1
import numpy as np
a = np.arange(12).reshape(4, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
b = np.arange(3)
print(b)

[0 1 2]


In [30]:
# the broadcast working process is 
# [4 3]  [3]
# [4 3]  [1 3]
# [4 3]  [4 3]

print(a+b)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [33]:
# example 2
import numpy as np
a = np.arange(3).reshape(1, 3)
print(a)

[[0 1 2]]


In [32]:
b = np.arange(3).reshape(3, 1)
print(b)
# [1 3] [3 1]
# [3 3] [3 3]

[[0]
 [1]
 [2]]


In [34]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [36]:
# example 3
import numpy as np
a = np.arange(16).reshape(4, 4)
print(a)
# [[ 0  1  2  3] 
#  [ 4  5  6  7] 
#  [ 8  9 10 11] 
#  [12 13 14 15]]

b = np.arange(4).reshape(2, 2)
print(b)
# [[0 1] 
#  [2 3]]

print(a+b)  # it will not execute 