# Numpy Indexing Array

In [1]:
#1-D Array indexing is the same as accessing an array element. strat with 0, second 1
import numpy as np
sourov = np.array([1, 2, 3, 4])
print(sourov[1])


2


In [2]:
# we can get the third and forth elements from adding them
import numpy as np
sourov = np.array([1, 2, 3, 4])
print(sourov[2] + sourov[3])

7


In [3]:
# Accessing the 2 -D - it is like a rows and columns.
import numpy as np
sourov = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#print('2nd element in the 1st rows', sourov[0, 1])
print('5th element in the 2nd rows', sourov[1, 4])


5th element in the 2nd rows 10


In [4]:
# accessing the 3-D - same as accessing

import numpy as np
sourov = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12 ]]])
print("2nd elemnt in 3rd row is :", sourov[1, 0, 1])
print("3rd elemnt of 1st row is :", sourov[0, 0, 2])


2nd elemnt in 3rd row is : 8
3rd elemnt of 1st row is : 3


In [5]:
#Numpy Advance indexing 
import numpy as np
x = np.arange(12).reshape(4, 3)
print(x)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
### Fancy Indexing
# find 1st, 3rd, 4rth
print(x[[0, 2, 3]])


[[ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:

import numpy as np
y = np.arange(24).reshape(6, 4)
print(y)

# execute 1st 3rd 6rth 
print(y[[0,2,5]])

# execute 1st 2nd 3rd column
print(y[:,[0, 2, 3]])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [20 21 22 23]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [8]:
### Boolean indexing
import numpy as np
x = np.random.randint(1,100, 24).reshape(6, 4)
# means random integer range 1 - 100, item 24,  reshape 6 row 4 column
print(x)


[[36 15 64 86]
 [48 23 96 13]
 [15 18 52 28]
 [27 14 89 64]
 [44 64 40 77]
 [71 57 39 19]]


In [9]:

###find all numbers greater than 50
print(x>50)


[[False False  True  True]
 [False False  True False]
 [False False  True False]
 [False False  True  True]
 [False  True False  True]
 [ True  True False False]]


In [10]:
print(x[x>50])
# array([79 72 73 54 94 60 66 83 61 84 97 78 
# 90])


[64 86 96 52 89 64 64 77 71 57]


In [11]:
### find all even number
print(x[x % 2 == 0])

[36 64 86 48 96 18 52 28 14 64 44 64 40]


In [12]:
### find all even and greater thatn 50
print(x[(x > 50) & (x % 2 == 0)])   # & this and use cz we use boolean

[64 86 96 52 64 64]


In [13]:
### find all number not divisible by 7
print(x[x % 7 == 0])

[28 14 77]


In [14]:
### find all number  divisible by 7
print(x[~(x % 7 == 0)])            # ~ boolean not , | boolean or

[36 15 64 86 48 23 96 13 15 18 52 27 89 64 44 64 40 71 57 39 19]
