# Numpy Array Slicing

In [1]:
# slicing array - slicing in python means taking elemetns from one given index to another index.
# [start:end], [start:end:step]

In [2]:
# now we will slice an element from 1 to 5 :
import numpy as np
sourov = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sourov[1:5])

[2 3 4 5]


In [3]:
# now we will slice from index 4 to the end value
import numpy as np
sourov = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sourov[4:])

[5 6 7 8 9]


In [4]:
# now we will slice the element from the begining to index 4
import numpy as np
sourov = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sourov[:4])

[1 2 3 4]


In [5]:
# Negative Slicing - index 3 to end
import numpy as np
sourov = np.array([1, 2, 3, 4, 5, 6, 7])
print(sourov[-3:-1])

[5 6]


In [6]:
# Step: you will use step value to determine the step of the slicing
# return every other value from index 1 to 5
import numpy as np
sourov = np.array([1, 2, 3, 4, 5, 6, 7])
print(sourov[1:5:2])

[2 4]


In [7]:
# now return every other number from the entire array
import numpy as np
sourov = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sourov[::2])

[1 3 5 7 9]


In [8]:
# slicing 2-D Array:
import numpy as np
sourov = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(sourov[1,1:4])

[7 8 9]


In [9]:
# another example
import numpy as np
sourov = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(sourov[0:2, 2])

# another example tough 2-D 
import numpy as np
sourov = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(sourov[0:2, 1:4])
print(sourov[0:2, 0:5])

# np.put()  : function repalce specific elements of an array with given values of p_array. Array index work on flattened
import numpy as np
x = np.array([1, 2, 5, 6, 4, 3, 6, 6])
y = np.put(x, [0, 3],[100, 500])  # permanent change
print(x)
# [100   2   5 500   4   3   6   6]


[3 8]
[[2 3 4]
 [7 8 9]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[100   2   5 500   4   3   6   6]


In [10]:
# np.delet()
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
y = np.delete(x, [0, 3, 5, 6])   # dont change original array
print(y)
# [2 3 5 8 9]


[2 3 5 8 9]


In [12]:
# np.clip() : it used to clim(limit) the values in an array
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
y = np.clip(x, a_min=5, a_max=10)
print(y)

[ 5  5  5  5  5  6  7  8  9 10 10 10 10 10 10]
