# Numpy Array Reshaping

In [1]:
# reshaping - means changing the shape of an array ,like adding or removing the elements.

# reshaping from 1-D to 2-D
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(4, 3)
z = x.reshape(6, 2)
print(y)
print(z)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [2]:
# reshping from 1-D to 3-D
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(2, 3, 2)
print(y)
p = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(p.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(3, 2, 2)


In [3]:
# Return copy or view
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
print(x.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [4]:
# unknown dimension - you are only allowed to have one unknown dimension. pass -1.
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
y = x.reshape(2, 2, -1)
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Flattening the array by converting multidimensional array in 1-D.
import numpy as np
x = np.array([[1,2,3], [4,5,6]])
y = x.reshape(-1)
print(y)

[1 2 3 4 5 6]


In [6]:
# expand_dims : get the expandant dimetions of array
import numpy as np
a = np.array([11, 53, 28, 50, 38, 37, 94, 92, 5, 30, 68, 9, 78, 2, 21])
# row wise (row vector)
b = np.expand_dims(a, axis=0) #
print(b)
print(b.shape)

[[11 53 28 50 38 37 94 92  5 30 68  9 78  2 21]]
(1, 15)


In [7]:
#column wise(column vector)
c = np.expand_dims(a, axis=1)
print(c)
print(c.shape)

# there are alot of functions for changing the shapes pf an array in numpy. like flatten, ravel and also rearranging the element rot90, flip,fliplr, flipud. they all are actually comes under advanced numpy.

[[11]
 [53]
 [28]
 [50]
 [38]
 [37]
 [94]
 [92]
 [ 5]
 [30]
 [68]
 [ 9]
 [78]
 [ 2]
 [21]]
(15, 1)
